# config/settings.yaml

proxy: "http://127.0.0.1:7890"

vlm_parser:
  batch_size: 20
  batch_polling_timeout_seconds: 28800 # 8 hours
  sleep_interval: 600
  parsing_prompt_path: "config/prompts/pdf_parsing.md"
  state_file_path: "data/cache/processing_state.json"
  input_dir: "data/raw_pdfs/"
  output_dir: "data/processed_jsons/"

llm:
  provider: google
  model: gemini-2.5-pro
  api_key: ${GEMINI_API_KEY}
  batch_mode: true                 # 是否启用批处理
  temperature: 0.1                 # 控制生成的稳定性
  top_p: 0.9

  pdf_parser:
    input_dir: "data/raw_pdfs"
    output_dir: "data/processed_jsons"

loader:
  source_json_dir: "data/processed_jsons/"
  output_dir: "data/chunks/"
  output_format: "jsonl"  # jsonl, json, or parquet
  chunk_size: 500  # 每个文本块的目标大小 (字符数)
  chunk_overlap: 100  # 相邻文本块之间的重叠大小 (字符数)
  filename_map:
    jsonl: "text_units.jsonl"
    json: "text_units.json"
    parquet: "text_units.parquet"

extraction:
  input_dir: "data/chunks"
  input_filename: "text_units.jsonl"
  output_dir: "data/graphs/extracted"
  output_filename: "extracted_graph.jsonl"
  requests_dir: "data/cache" # 临时存放批量请求文件的目录
  prompt_path: "config/prompts/text_to_graph.md"

graph_builder:
  input_path: "data/graphs/extracted/extracted_graph.jsonl"
  disambiguation_graph_path: "data/graphs/disambiguation_graph.json"
  merge_graph_path: "data/graphs/merged_graph.json"
  output_graph_path: "data/graphs/final_graph.json"
  community_reports_path: "data/reports/community_summaries.jsonl"
  disambiguation_requests_path: "data/cache/disambiguation_requests.jsonl"
  embedding_requests_path: "data/cache/entities_embedding_requests.jsonl"
  merge_requests_path: "data/cache/entities_merge_requests.jsonl"
  community_requests_path: "data/cache/community_detection.jsonl"
  prompt_dir: "config/prompts"

  sleep_interval: 600
  community_summary_max_report_words: 1000
  community_summary_used_entities_num: 25
  community_summary_used_relationships_num: 50
  community_importance_weight_alpha: 0.6 # 重要性权重的alpha值
  enable_entity_merge: True
  entity_merge_topk: 10
  entity_merge_min_sim: 0.82

embedding:
  model: "gemini-embedding-001"
  dimensionality: 768
  input_text_units_path: "data/chunks/text_units.jsonl"
  input_graph_path: "data/graphs/final_graph.json"
  input_community_report_path: "data/reports/community_summaries.jsonl"
  output_db_path: "data/embeddings/embeddings.db"
  output_db_text_path: "data/embeddings/text.db"
  output_text_table_name: "text"
  requests_path: "data/cache"
  sleep_interval: 600

query:
  top_k: 5
  generation_model: "gemini-2.5-flash"
  temperature: 0.1
  top_p: 0.9
  search_config: false # allow_general_knowledge or not

  text_db_path: "data/embeddings/text.db"
  text_table_name: "text"
  output_dir: "data/answers"
  output_filename: "answers_text.jsonl"
  requests_path: "data/cache"
  sleep_interval: 600
  basic_rag_prompt: "config/prompts/basic_rag.md"

  embedding_db_path: "data/embeddings/embeddings.db"
  global_table_name: "communities"
  local_table_name: "entities"
  prompt_dir: "config/prompts"

  input_graph_path: "data/graphs/final_graph.json"
  input_community_report_path: "data/reports/community_summaries.jsonl"

database:
  graphdb:
    type: neo4j
    uri: "bolt://localhost:7687"
    username: "neo4j"
    password: "123456789"

logging:
  level: INFO                      # DEBUG / INFO / WARNING / ERROR
  log_file: "logs/superalloyKgRAG.log"

evaluation:
  qa_pairs_path: "data/evaluation_sets/qa_pairs.csv"
  ground_truth_path: "data/evaluation_sets/ground_truth.json"
  metrics: ["faithfulness", "relevance", "factual_accuracy"]
